### ISSUE TITLE
OnNotificationOpened in Android fired unneccesarily when not in Active USB Debugging

### ISSUE THREAD

**Issue by muhaym** [CrossGeeks/PushNotificationPlugin#49] opened 2018-02-24 06:47 UTC
I have been using this plugin and testing it. One issue I have found is that (which is very hard to recreate)

OnNotificationOpened fires everytime the App launch even without any notification, and navigates to the page which we have given in the event. This breaks the usability of app.

The issue though is not found when we are debugging with USB connected. It will occur when we open the app directly after a debug session and it repeats everytime. Also reproduced in Release mode too.

Some Insights I tried to gain: The dictionary p.Data is not null, it contains Key: "profile" Value "0". 

Any idea why this is happening? This issue is not there in iOS

**Comment by rdelrosario** [comment] 2018-02-24 14:34
Do you have a SplashActivity?

**Comment by muhaym** [comment] 2018-02-24 14:35
Yes

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by rdelrosario** [comment] 2018-02-24 14:35
Where are you calling ProcessIntent?

**Comment by muhaym** [comment] 2018-02-24 15:11
Hi, sorry for wrong info, we are using Splash Screen with changing App Theme technique.

For calling ProcessIntent, it's after Load application() in MainActivity

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by rdelrosario** [comment] 2018-02-24 15:28
How are you loading the MainActivity from the Splash? Using SingleTop flag?

**Comment by rdelrosario** [comment] 2018-02-24 15:28
Also are you calling processintent on MainActivity OnNewIntent?

**Comment by rdelrosario** [comment] 2018-02-24 15:29
You are not using OnNotificationReceived right?

**Comment by muhaym** [comment] 2018-02-26 04:39
@rdelrosario I am not calling it in OnNewIntent, instead in MainActivity OnCreate.

Using OnNotificationReceived in my PCL project which just have Debug.WriteLine("Received").

I don't have seperate Splash Activity, I'm using https://xamarinhelp.com/creating-splash-screen-xamarin-forms/ (Better Approach), which sets theme initially to splash screen, and once Loaded, theme is changed.

SingleTop flags are there for Xamarin Auth related stuff, nothing in MainActivity.

**Comment by rdelrosario** [comment] 2018-02-26 20:46
What code do you have OnNotificationReceived?

**Comment by muhaym** [comment] 2018-02-27 12:19
Just Debug.WriteLine("NotificationReceived");

**Comment by rdelrosario** [comment] 2018-02-27 13:00
How you know is triggering multiple times then? If not debugging

**Comment by muhaym** [comment] 2018-02-27 13:39
In OnNotificationOpened, I have code to Navigate to certain Page, so without debug mode, when the app is opened, it directly navigates to that page.

**Comment by rdelrosario** [comment] 2018-02-27 18:41
Can you put here that code block?

**Comment by muhaym** [comment] 2018-02-28 06:24
CrossPushNotification.Current.OnNotificationOpened += async (s, p) =>
                            {
                                var lines = p.Data.Select(kvp => kvp.Key + ": " + kvp.Value.ToString());
                                Analytics.TrackEvent("Fired Unneccessarily", new Dictionary<string, string> {
                                { "Push Data", string.Join(Environment.NewLine, lines)
                            },
                                { "Identifier", p.Identifier},
                                { "Type",p.Type.ToString()}
        });
                                System.Diagnostics.Debug.WriteLine("Opened");
                                if (!p.Data.ContainsKey("profile"))
                                {
                                    foreach (var data in p.Data)
                                        System.Diagnostics.Debug.WriteLine($"{data.Key} : {data.Value}");
                                    if (account.GetCurrentUser() != null)
                                    {
                                        bool IsAdmin = account.GetCurrentUser().IsAdmin;
                                        if (IsAdmin)
                                            await _navigator.PushAsync<MessageListViewModel>();
                                        else await _navigator.PushAsync<OPMessageListViewModel>();
                                    }
                                }
                            };

**Comment by rdelrosario** [comment] 2018-02-28 19:26
So the reason might be that just before you opened the application you received a notification but didn't opened, if you open the application you will get the notification anyways because there's a feature called delayed response which processes any pending notification when application opened. To disable this feature call ProcessIntent with false on the second parameter:

```cs
ProcessIntent(Intent intent,false);
```

**Comment by rdelrosario** [comment] 2018-03-04 13:44
Are you still having this issue?

**Comment by muhaym** [comment] 2018-03-06 14:01
I don't think this is because of delayed response, though I am using the old ProcessIntent, will update and check whether this solve the issue.

**Comment by rdelrosario** [comment] 2018-03-14 16:39
Did you solve your issue?

**Comment by rdelrosario** [comment] 2018-03-18 03:59
Will close this for now because can't reproduce, if still happening for you feel free to reopen it.

**Closed by rdelrosario** 2018-03-18 03:59 UTC

**Comment by harindaka** [comment] 2018-09-20 07:55
@muhaym we ran into the same exact behavior and issue in our app in development. However, we were able to solve it. The key is in the phrase 

"If you disable this just make sure you are subscribed to OnNotificationOpened before this call occurs, a good place might be on App.cs constructor because OnStart is called after"

The solution is simply to

1. Call ProcessIntent passing "false" as advised by @rdelrosario 
2. Ensure the OnNotificationOpened event registration code (event += handler line) executes before the ProcessIntent call in MainActivity.OnCreate. In my case moving the OnNotificationOpened event registration code (event += handler line) from App_Start to App.xaml.cs constructor as @rdelrosario worked. 
3. Note that if you do navigation inside the OnNotificationOpened event handler, since that and App_Start seems to run asynchronously, any navigation logic placed in App_Start may conflict each other and prevent expected navigation behavior. To solve this simply synchronize the App_Start and OnNotificationOpened event handler code using a TaskCompletionSource (promise)

Hope this helps anyone else running into this issue.
