### ISSUE TITLE
System.ArgumentOutOfRangeException after OnNotificationReceived()

### ISSUE THREAD

**Issue by javilopezruiz** [CrossGeeks/PushNotificationPlugin#19] opened 2017-11-25 13:03 UTC
I am getting this error just after OnNotificationReceived() is executed in Android 7 device:

<img width="581" alt="captura de pantalla 2017-11-25 a les 14 01 25" src="https://user-images.githubusercontent.com/11061347/33230728-5a00fbc8-d1e9-11e7-8a99-463a538475f4.png">

It happens when the app is in foreground. If the app is in background all works fine..
Any idea of why is this happening?

**Comment by rdelrosario** [comment] 2017-11-25 13:59
What payload are you sending?

**Comment by rdelrosario** [comment] 2017-11-25 14:02
Posible duplicate of: #13

**Comment by javilopezruiz** [comment] 2017-11-25 14:35
I am sending this notification always:

'notification' => [
         'title'=>'This is the title',
         'body'=>'This is the message',
         'sound' => 'default'
]

And the error appears when app in foreground only. 

Version of your plugin: 1.1.2

**Comment by javilopezruiz** [comment] 2017-11-25 14:49
It has to do with the sound.. 
If I delete the 'sound' key, then everything works fine in foreground and the device sounds when getting the notification.. but when app is not in foreground the device does not sound when it receives the push notification

What can I do to solve this?

**Comment by javilopezruiz** [comment] 2017-11-25 15:14
Okay, solved. If you send this using FCM it works perfect in background and in foreground:
'data' => [
                   'title'=>'This is the title',
                   'body'=>'This is the message'
]

**Comment by javilopezruiz** [comment] 2017-11-25 18:10
I realized that notification is not received when app is killed. Using data message in notification payload in FCM.

And you say in your documentation:

<img width="906" alt="captura de pantalla 2017-11-25 a les 19 08 55" src="https://user-images.githubusercontent.com/11061347/33233303-36a499c0-d214-11e7-9d91-3c0efd982f1b.png">

Why I am not receiving it when app is killed?

**Comment by rdelrosario** [comment] 2017-11-26 01:16
The exception issue was happening when using sound on the payload. Should be fixed on latest release: https://www.nuget.org/packages/Plugin.PushNotification/1.1.5.

About the other issue, please open a new one and let me know what are you doing on the OnNotificationReceived and if is a Xamarin Forms application.

**Closed by rdelrosario** 2017-11-26 01:16 UTC
